/* Archivo auto-generado por Python */
const DASHBOARD_DATA = {
    "meta": {
        "updated": "6/octubre/2026",
        "edt": 43
    },
    "expectedItems": [
        "1 OBL-01: APROBACION EQUIPO DE TRABAJO",
        "1.1 Conformacion y validacion del equipo (Bolsa 1)",
        "1.1.1 Entrega de hojas de vida y soportes del equipo",
        "1.1.2 Reunion de inicio y presentacion del proyecto",
        "2 OBL-02: PLAN DE GESTION DEL PROYECTO",
        "2.1 Gestion integral del proyecto SALVIA Web (Bolsa 1)",
        "2.1.1 Presentacion, aprobacion y uso del Mockup Kreivo-SALVIA",
        "2.1.2 Firma de Acta de Alcance y SLA",
        "2.1.3 Levantamiento: Modulo Web ASP - Variables de Riesgo",
        "2.1.4 Gantt y plan de trabajo Kreivo-SALVIA",
        "2.2 Gestion integral del proyecto App MASP (Bolsa 2)",
        "2.2.1 App MASP: diseno de interfaz segura",
        "2.2.2 App MASP: diseno de alertas y Push Notifications",
        "2.2.3 App MASP: integracion con core SALVIA",
        "3 OBL-03: METODOLOGIA DE DESARROLLO DE SOFTWARE",
        "3.1 Metodologia de desarrollo - SALVIA Web (Bolsa 1)",
        "3.1.1 Diseno y logica: Landing Page, Login y Captcha",
        "3.1.2 Logica y arbol de decision: Modulo de Tamizaje (escala severidad)",
        "3.1.3 Refinamiento UX: Dashboard y trazabilidad de casos",
        "3.2 Metodologia de desarrollo - App MASP (Bolsa 2)",
        "3.2.1 Diseno de flujos y UI: App Movil MASP",
        "3.2.2 Aprobacion de Arquitectura e Interoperabilidad",
        "4 OBL-04: ANALISIS, DISENO Y REQUERIMIENTOS",
        "4.1 Documentacion previa y auditoria (Bolsa 1)",
        "4.1.1 Documentacion y metodologia SALVIA Web heredada",
        "4.1.2 Historias de Usuario actuales (sistema heredado)",
        "4.1.3 Arquitectura actual y diagnostico de deuda tecnica",
        "4.2 Analisis y diseno SALVIA Web (Bolsa 1)",
        "4.2.1 Arquitectura SOG hacia EAV-DAG",
        "4.2.2 Casos de uso e Historias de Usuario (interconectividad y flujo)",
        "4.2.3 Diagramas Figma y diccionario de datos (SALVIA Web)",
        "4.2.4 Actas de mesas tecnicas",
        "4.2.5 Historias de Usuario ancladas a Figma",
        "4.2.6 Migracion de Kobo a Zenkit (analisis solucion transitoria)",
        "4.2.7 Integracion data SOG hacia EAV-DAG",
        "4.2.8 Documentacion y metodologia App MASP",
        "4.3 Analisis y diseno App MASP (Bolsa 2)",
        "4.3.1 Diagramas Figma y diccionario de datos (App MASP)",
        "5 OBL-05: DESARROLLO DE MODULOS SALVIA",
        "5.1 Sprints de construccion SALVIA Web (Bolsa 1)",
        "5.1.1 Sprint 1: Setup de entornos, BD y seguridad (autenticacion)",
        "5.1.2 Sprint 2: Modulos de registro y motor de tamizaje",
        "5.1.3 Sprint 3: Dashboard de trazabilidad y alertas",
        "5.1.4 Sprint 5: Integracion SIVIGE (interoperabilidad)",
        "5.2 Sprints de construccion App MASP (Bolsa 2)",
        "5.2.1 Sprint 4: Desarrollo App MASP (iOS / Android)",
        "5.2.2 Ejecucion de pruebas unitarias y de carga (sprint)",
        "6 OBL-06: ACOMPANAMIENTO EN FASES DE DESARROLLO",
        "6.1 Acompanamiento SALVIA Web (Bolsa 1)",
        "6.1.1 BI: Diseno de Dashboards y ETL",
        "6.1.2 Adopcion: manuales y capacitacion (SALVIA Web)",
        "6.1.3 Setup entornos, BD Postgres y seguridad (SALVIA)",
        "6.1.4 Modulo de recepcion y motor de tamizaje (web)",
        "6.1.5 Modulo de seguimiento y tableros BI/ETL (web)",
        "6.1.6 Modulo LGBTIQ+ (construccion y variables diferenciales)",
        "6.1.7 Modulo ASP Web - caracterizacion y analisis de riesgo",
        "6.2 Acompanamiento App MASP (Bolsa 2)",
        "6.2.1 Despliegue: migracion a produccion (App)",
        "6.2.2 Soporte: activacion de mesa de ayuda",
        "6.2.3 Ejecucion de pruebas unitarias y de carga (App)",
        "6.2.4 Setup de entornos y seguridad API (App MASP)",
        "6.2.5 Desarrollo de interfaz y logica de App Movil MASP",
        "6.2.6 Desarrollo backend - Boton de Panico Linea 155",
        "6.2.7 Integracion App - Boton de Panico Linea 155",
        "7 OBL-07: PRUEBAS FUNCIONALES Y NO FUNCIONALES",
        "7.1 Pruebas SALVIA Web (Bolsa 1)",
        "7.1.1 Pruebas de Aceptacion de Usuario (UAT) con el Ministerio",
        "7.1.2 Transferencia de conocimiento y capacitacion inicial",
        "7.1.3 Paso a produccion oficial SALVIA",
        "7.1.4 API de sincronizacion SIVIGE (Minsalud)",
        "7.1.5 QA unitarias, carga y vulnerabilidad (SALVIA Web)",
        "7.1.6 Pruebas de Aceptacion de Usuario UAT (SALVIA Web)",
        "7.2 Pruebas App MASP (Bolsa 2)",
        "7.2.1 Ajustes Post-UAT y estabilizacion",
        "7.2.2 Publicacion App MASP en stores",
        "7.2.3 QA unitarias, estres y vulnerabilidad (App MASP)",
        "7.2.4 Pruebas de Aceptacion de Usuario UAT (App MASP)",
        "8 OBL-08: CONFIGURACION EN PRODUCCION",
        "8.1 Configuracion productiva SALVIA Web (Bolsa 1)",
        "8.1.1 Migracion RedHat y recibo en produccion (SALVIA)",
        "8.1.2 Manuales y capacitaciones a funcionarios (SALVIA)",
        "8.1.3 Registro ante la DNDA (propiedad intelectual web)",
        "8.2 Configuracion productiva App MASP (Bolsa 2)",
        "8.2.1 Despliegue de APIs a produccion (MASP)",
        "8.2.2 Manuales y videos de uso App (MASP)",
        "8.2.3 Publicacion oficial en Play Store / App Store",
        "9 OBL-09: RECIBO A SATISFACCION EN PRODUCCION",
        "9.1 Recibo productivo SALVIA Web (Bolsa 1)",
        "9.1.1 Validacion final de migracion RedHat y recibo (SALVIA)",
        "9.1.2 Validacion final de manuales y capacitaciones (SALVIA)",
        "9.1.3 Validacion final del registro ante DNDA",
        "9.2 Recibo productivo App MASP (Bolsa 2)",
        "9.2.1 Validacion final de despliegue de APIs (MASP)",
        "9.2.2 Validacion final de manuales y videos de uso App",
        "9.2.3 Validacion final de publicacion en tiendas",
        "10 OBL-10: REGISTRO ANTE DNDA (DERECHOS DE AUTOR)",
        "10.1 Registro DNDA - SALVIA Web (Bolsa 1)",
        "10.1.1 Preparacion de documentacion tecnica para DNDA (Web)",
        "10.1.2 Radicacion y seguimiento DNDA (Web)",
        "10.2 Registro DNDA - App MASP (Bolsa 2)",
        "10.2.1 Preparacion de documentacion tecnica para DNDA (App)",
        "10.2.2 Radicacion y seguimiento DNDA (App)",
        "11 OBL-11: REGISTRO APP EN TIENDAS (PLAY STORE / APP STORE)",
        "11.1 Gestion de cuentas y repositorios oficiales",
        "11.1.1 Compra y configuracion de cuenta Play Store",
        "11.1.2 Compra y configuracion de cuenta App Store",
        "11.2 Publicacion y certificacion en tiendas",
        "11.2.1 Publicacion oficial en Play Store",
        "11.2.2 Publicacion oficial en App Store",
        "12 OBL-12: CAPACITACIONES Y APROPIACION",
        "12.1 Capacitaciones SALVIA Web (Bolsa 1)",
        "12.1.1 Plan de capacitacion SALVIA Web",
        "12.1.2 Capacitaciones masivas a Linea 155 y gestoras",
        "12.1.3 Encuestas de adopcion y apropiacion (Web)",
        "12.2 Capacitaciones App MASP (Bolsa 2)",
        "12.2.1 Plan de capacitacion App MASP",
        "12.2.2 Capacitaciones a usuarias y coordinadoras",
        "12.2.3 Encuestas de adopcion y apropiacion (App)",
        "13 OBL-13: GOBERNANZA CONTINUA - COMITES TECNICOS",
        "13.1 Gobernanza SALVIA Web (Bolsa 1)",
        "13.1.1 Comites tecnicos, gestion de riesgos y reportes (Bolsa 1)",
        "13.2 Gobernanza App MASP (Bolsa 2)",
        "13.2.1 Comites tecnicos, gestion de riesgos y reportes (Bolsa 2)"
    ],
    "itemProgress": [
        100,
        100,
        100,
        100,
        74,
        79,
        100,
        75,
        50,
        90,
        67,
        100,
        75,
        25,
        75,
        75,
        100,
        50,
        75,
        75,
        100,
        50,
        82,
        100,
        100,
        100,
        100,
        79,
        100,
        75,
        75,
        90,
        60,
        100,
        80,
        50,
        60,
        60,
        47,
        55,
        100,
        60,
        60,
        0,
        30,
        60,
        0,
        42,
        44,
        40,
        10,
        100,
        50,
        85,
        25,
        0,
        41,
        60,
        0,
        0,
        90,
        60,
        50,
        25,
        26,
        29,
        30,
        25,
        60,
        0,
        30,
        30,
        22,
        40,
        50,
        0,
        0,
        17,
        0,
        0,
        0,
        0,
        33,
        50,
        0,
        50,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        31,
        25,
        50,
        0,
        38,
        75,
        0,
        4,
        8,
        25,
        0,
        0,
        0,
        0,
        0,
        0,
        90,
        90,
        90,
        90,
        90
    ],
    "milestones": [
        {
            "id": "H01",
            "name": "MODULO SEGUIMIENTO",
            "date": "2026-06-18",
            "completion": 69,
            "signature": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                3,
                2,
                2,
                2,
                3,
                0,
                2,
                3,
                3,
                3,
                0,
                2,
                3,
                2,
                2,
                2,
                2,
                3,
                2,
                0,
                0,
                0,
                2,
                2,
                0,
                2,
                2,
                1,
                0,
                0,
                0,
                2,
                2,
                2,
                0,
                3,
                2,
                2,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: Seguimiento, Barreras, Notificaciones, Tareas y Atención Psicosocial están en producción; Rutas y gestión institucional está en pruebas. Pendiente: 42 hallazgos de Seguimiento y 25 de Psicosocial siguen en curso en la bitácora del 1-oct, 5 de ellos críticos; Medidas de Emergencia no tiene desarrollo y depende de que el Ministerio apruebe mockups y criterios. Riesgo: la rama main no recibe cambios desde el 10-sep, así que varias correcciones de septiembre no están en producción. Nota: la EDT no tiene una fila propia para Medidas de Emergencia, por lo que el porcentaje no refleja ese pendiente.",
            "responsable": "Brayan Marbello / Juan Buitrago"
        },
        {
            "id": "H02",
            "name": "MODULO FEMINICIDIO",
            "date": "2026-07-15",
            "completion": 67,
            "signature": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                3,
                2,
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                2,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                0,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: operan la parametrización de tiempos por nivel de riesgo, la clasificación alto/bajo y la asignación automática al agente. Pendiente: calibrar el tamizaje desde el formulario de registro, incorporar las variables adicionales y validar la lógica de clasificación; familiares y personas huérfanas (Ley 2530 de 2025) se atienden dentro de Medidas de Emergencia y están en mockup. Riesgo: depende de reglas y criterios de aceptación del Ministerio. Nota: la EDT no tiene filas para familiares y personas huérfanas, por lo que el porcentaje no refleja ese pendiente.",
            "responsable": "Brayan Marbello"
        },
        {
            "id": "H03",
            "name": "MODULO ASP (SALVIA WEB)",
            "date": "2026-08-14",
            "completion": 25,
            "signature": [
                0,
                0,
                0,
                0,
                2,
                2,
                0,
                0,
                2,
                0,
                2,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: variables de riesgo documentadas en julio. Pendiente: todo el desarrollo del módulo web. Decisión: la solicitud de prórroga del 22-sep reconoce el módulo como alcance contractual, declara que su desarrollo integral no es viable con las horas disponibles y pide a la Supervisión definir su tratamiento. Riesgo: los lineamientos, mockups y criterios de la Dirección de Actividades Sexuales Pagas no se han recibido.",
            "responsable": "Santiago Ramos / Juan Buitrago"
        },
        {
            "id": "H04",
            "name": "MODULO LGBTIQ+",
            "date": "2026-08-14",
            "completion": 25,
            "signature": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: secciones OSIGHN construidas en los formularios de psicosocial el 17-sep. Pendiente: MVP acordado para la prórroga, limitado a incluir las preguntas de esta población en el formulario de registro y en los de seguimiento; falta la lista cerrada de preguntas. Riesgo: la pregunta OSIGHN aparece hoy donde no corresponde (hallazgo PSI-24).",
            "responsable": "Brayan Marbello / Juan Buitrago"
        },
        {
            "id": "H05",
            "name": "APP MOVIL MASP",
            "date": "2026-08-26",
            "completion": 48,
            "signature": [
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                2,
                3,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                2,
                3,
                2,
                2,
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                1,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                1,
                2,
                2,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                0,
                2,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                1,
                2,
                2,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: lista de contactos, Home, información de programas y rediseño visual (16-sep); la app apunta al dominio productivo y se subió una nueva versión Android el 23-sep; el informe del 17-sep reporta Seguridad y SOS en Play Store. Pendiente: directorio de entidades, sincronización y bitácora, integración con la Línea 155, App Store, QA y UAT. Decisión: la prórroga solo cubre cerrar lo ya desarrollado, sin pantallas nuevas.",
            "responsable": "Santiago Ramos"
        },
        {
            "id": "H06",
            "name": "ARQUITECTURA EAV-DAG",
            "date": "2026-05-14",
            "completion": 90,
            "signature": [
                0,
                0,
                0,
                0,
                2,
                2,
                3,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                3,
                0,
                0,
                2,
                0,
                2,
                2,
                3,
                3,
                3,
                3,
                2,
                3,
                0,
                2,
                0,
                0,
                0,
                2,
                0,
                0,
                0,
                2,
                2,
                3,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: arquitectura EAV-DAG implementada y sosteniendo los módulos en producción. Pendiente: casos migrados con formularios vacíos o sin esquema de seguimiento (SEG-01 y SEG-02), que requieren script en producción. Riesgo: el mecanismo de interoperabilidad con SIVIGE sigue sin definición técnica.",
            "responsable": "Andres Posada / Andres Ascencio"
        },
        {
            "id": "H07",
            "name": "GOBERNANZA Y GESTION DEL PROYECTO",
            "date": "2026-10-30",
            "completion": 85,
            "signature": [
                3,
                3,
                3,
                3,
                2,
                2,
                3,
                2,
                2,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                3,
                3,
                3,
                3,
                2,
                3,
                2,
                2,
                2,
                2,
                3,
                2,
                2,
                0,
                0,
                2,
                2,
                3,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                2,
                2
            ],
            "details": "Avance: solicitud de prórroga hasta el 15-dic radicada el 22-sep, con informe de alcance y riesgos del 17-sep; bitácora de ajustes con 112 ítems, sesiones de revisión con SALVIA y formulario de hallazgos en uso; 3.924 de 5.396 horas ejecutadas a agosto (72,7 %). Pendiente: decisión de la Supervisión sobre la prórroga y el tratamiento de ASP, control de cambios para los nuevos requerimientos y cronograma actualizado. Riesgo: el plazo vigente vence el 26-oct.",
            "responsable": "Andres Posada"
        },
        {
            "id": "H08",
            "name": "QA Y PRUEBAS",
            "date": "2026-08-31",
            "completion": 26,
            "signature": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                3,
                0,
                2,
                1,
                2,
                0,
                1,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                1,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                0,
                0,
                0,
                2,
                2,
                2,
                2,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: primera iteración de QA de Rutas, cuatro mesas de hallazgos con SALVIA el 30-sep y 24 reportes por el formulario. Pendiente: UAT formal del alcance contractual, pruebas de estrés, seguridad y accesibilidad; QA y UAT de la app. Riesgo: las pruebas de punta a punta de Rutas están bloqueadas por falta de usuarios y datos de prueba (RUT-17); en septiembre el 41 % del trabajo en código fue reproceso.",
            "responsable": "Brayan Marbello"
        },
        {
            "id": "H09",
            "name": "DESPLIEGUE EN PRODUCCION",
            "date": "2026-10-31",
            "completion": 38,
            "signature": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                3,
                0,
                2,
                1,
                2,
                2,
                1,
                2,
                2,
                0,
                0,
                3,
                0,
                0,
                0,
                0,
                2,
                2,
                1,
                0,
                2,
                0,
                0,
                0,
                2,
                2,
                0,
                0,
                2,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                1,
                1,
                0,
                0,
                2,
                2,
                0,
                0,
                1,
                1,
                1,
                0,
                0,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: Seguimiento, Barreras, Notificaciones, Tareas y Psicosocial en producción; app Android publicada. Pendiente: salida de Rutas a producción con regresión sobre Seguimiento, carga masiva de entidades, recibo a satisfacción. Riesgo: solo 9 de los 58 commits de trabajo de septiembre llegaron a main; hay que confirmar desde qué rama se despliega.",
            "responsable": "Camilo Arias"
        },
        {
            "id": "H10",
            "name": "TRANSFERENCIA DE CONOCIMIENTO",
            "date": "2026-10-31",
            "completion": 5,
            "signature": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                1,
                0,
                1,
                0,
                2,
                0,
                1,
                0,
                1,
                1,
                0,
                1,
                0,
                1,
                0,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                2,
                2,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: sin manuales ni capacitaciones formales en los documentos revisados. Pendiente: documentación técnica, manuales, videos de la app y capacitaciones, previstos para el cierre. Riesgo: 33 de los 100 hallazgos abiertos se resuelven con proceso o entendimiento, lo que indica que la capacitación no debería esperar al final.",
            "responsable": "Andres Ascencio / Brayan Marbello"
        },
        {
            "id": "H11",
            "name": "ENTREGA CONTRACTUAL Y DERECHOS DE AUTOR",
            "date": "2026-10-30",
            "completion": 17,
            "signature": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                2,
                0,
                2,
                0,
                0,
                2,
                1,
                0,
                0,
                1,
                2,
                0,
                0,
                2,
                1,
                1,
                0,
                0,
                1,
                1,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                2,
                2,
                2,
                1,
                2,
                2,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "details": "Avance: sin inicio. Pendiente: registro ante la DNDA, publicación final en tiendas y entrega del código fuente; el cronograma propuesto los ubica del 7 al 15-dic. Riesgo: con el plazo vigente al 26-oct no hay ventana para estas actividades si la prórroga no se aprueba.",
            "responsable": "Andres Posada"
        }
    ]
};
